name: Commit updated binary dependencies

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Build static library dependencies"]
    types:
      - completed
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.head_ref }}
      - shell: bash
        run: |
          rm -f deps/darwin_amd64/libduckdb.a
          rm -f deps/darwin_arm64/libduckdb.a
          rm -f deps/linux_amd64/libduckdb.a
          rm -f deps/linux_arm64/libduckdb.a
          rm -f deps/freebsd_amd64/libduckdb.a
          rm -f deps/windows_amd64/libduckdb.a
          rm -f duckdb.h
      - uses: actions/download-artifact@v4
        with:
          name: duckdb_h
          path: .
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: darwin_amd64
      #     path: deps/darwin_amd64
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: darwin_arm64
      #     path: deps/darwin_arm64
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: linux_amd64
      #     path: deps/linux_amd64
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: linux_arm64
      #     path: deps/linux_arm64
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: freebsd_amd64
      #     path: deps/freebsd_amd64
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: windows_amd64
      #     path: deps/windows_amd64
      - name: Push static libraries
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Re-build static libraries
          skip_fetch: true
          skip_checkout: true
#          branch: ${{ github.event.pull_request.head.ref || github.head_ref}}
